name: Cypress Tests
on: [push]
jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   env:
      UN: ${{ secrets.USERNAME }}
      PW: ${{ secrets.PASSWORD }}
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v3
 
     - name: Run Cypress Test
       uses: cypress-io/github-action@v5
       with:
         command: npx cypress run
         browser: chrome
